# Generated by Django 5.0.7 on 2024-07-18 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonApp', '0004_drinks_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='category_name', to='LittleLemonApp.menu'),
        ),
    ]
